INSERT INTO equipo VALUES (DEFAULT,'Rudolf Caracciola',3),(DEFAULT,'Bentley Motors Ltd',138),(DEFAULT,'Édouard Brisson',64),
(DEFAULT,'R. Parke',58),(DEFAULT,'Hon. Dorothy Paget',138),(DEFAULT,'Fox & Nicholl',138),(DEFAULT,'Earl Howe',138),(DEFAULT,'Lea-Francis Ltd',138),
(DEFAULT,'Marguerite Mareuse',64),(DEFAULT,'S.A des Automobiles Tracta',64),(DEFAULT,'Huskinson & Fane Ltd',138),(DEFAULT,' Francis Samuelson',138),
(DEFAULT,'V. Tatarinoff',146),(DEFAULT,'Henri de Costier',64),(DEFAULT,'Automobiles Ettore Bugatti',64),(DEFAULT,'Gerald Bevan',138),
(DEFAULT,'Roger Labric',64),(DEFAULT,'Peter Hope-Johnson',138),(DEFAULT,'S.A Alfa Romeo',86),(DEFAULT,'Antoine Schumann',64),
(DEFAULT,'Jean Sébilleau',64),(DEFAULT,'Aston Martin Ltd',138),(DEFAULT,' C. de Ricou',64),(DEFAULT,'Charles Charrier',64),(DEFAULT,'Joan Chetwynd',138),(DEFAULT,'Raymond Sommer',64),
(DEFAULT,'Arthur W. Fox',138),(DEFAULT,'Odette Siko',64),(DEFAULT,'Équipe de l''Ours',64),(DEFAULT,'Stanisław Czaykowski',136),(DEFAULT,'Just-Émile Vernet',64),(DEFAULT,'Charles Druck',64),
(DEFAULT,'Pierre-Louis Dreyfus',64),(DEFAULT,'Guy Bouriat',64),(DEFAULT,'H. Stoffel',64),(DEFAULT,'Prince Dimitri',67),(DEFAULT,'John Ludovic Ford',138),(DEFAULT,'Jean Danne',64),
(DEFAULT,'Henri de la Sayette',64),(DEFAULT,'Jean Trévoux',64),(DEFAULT,'Principe Nicholas of Romania',145),(DEFAULT,'Luigi Chinetti',86),(DEFAULT,'Louis Chiron',116),(DEFAULT,'Société des Automobiles Charley',64),
(DEFAULT,'André Rousseau',64),(DEFAULT,'Riley Motor Company Ltd.',138),(DEFAULT,'Alin Fréres',64),(DEFAULT,'Singer Motors',138),(DEFAULT,'N. Black',138),(DEFAULT,'H.B. Metchim',138),
(DEFAULT,'Norbert Jean Mahé',64),(DEFAULT,'Tim Rose-Richards',138),(DEFAULT,'Charles Brunet',64),(DEFAULT,'Max Fourney',64),(DEFAULT,'Louis Villeneuve',64),(DEFAULT,'Mrs. Gwenda Stewart',138),
(DEFAULT,'M.R.E. Tongue',138),(DEFAULT,'John Cecil Noël',138),(DEFAULT,'Frank Stanley Barnes',138),(DEFAULT,'A.A. Rigby',138),(DEFAULT,'Auguste Bodoignet',64),(DEFAULT,'Jean de Gavardie',64),
(DEFAULT,'Roy Eccles',138),(DEFAULT,'Miss Dorothy Champney',138),(DEFAULT,'Lord de Clifford',138),(DEFAULT,'Georges Boursin',64),(DEFAULT,'Charles Auguste Martin',64),(DEFAULT,'J.A. Grégoire',64),
(DEFAULT,'Raymond Gaillard',64),(DEFAULT,'Singer Ltd.',138),(DEFAULT,'Gordon Hendy',138),(DEFAULT,'R.P. Gardner',138),(DEFAULT,'Mme Anne-Cécile Rose-Itier',64),(DEFAULT,'Philippe Maillard-Brune',64),
(DEFAULT,'H. Bridgman Metchim',138),(DEFAULT,'Daniel Porthault',64),(DEFAULT,'Bernard de Souza Dantas',64),(DEFAULT,'Michel Paris',64),(DEFAULT,'Anthony Lago',64),(DEFAULT,'M. Rekip',64),
(DEFAULT,'Ecurie Argo',64),(DEFAULT,'Comte Georges d''Arnoux',64),(DEFAULT,'Derby',64),(DEFAULT,'Guy Don',138),(DEFAULT,'Tim Davies',138),(DEFAULT,'M.T.U. Collier',138),
(DEFAULT,'P.L. Donkin',138),(DEFAULT,'C.T. Thomas',138),(DEFAULT,'Maurice Faulkner',138),(DEFAULT,'André Hénon',64),(DEFAULT,'Maurice Baumer',138),(DEFAULT,'Eddie Hertzberger',18),
(DEFAULT,'Ecurie de l''Ours',64),(DEFAULT,'Amédée Gordini',64),(DEFAULT,'Gaston Duval',64),(DEFAULT,'Ian Connell',138),(DEFAULT,'J.R.H. Baker',138),(DEFAULT,'Guy Lapchin',64),
(DEFAULT,'Anthony Marsh',138),(DEFAULT,'Captain G.E.T. Eyston',138),(DEFAULT,'Philipee Maillard-Brune',64),(DEFAULT,'Austin',138),(DEFAULT,'John Carr',138),(DEFAULT,'Joseph Paul',64),
(DEFAULT,'Ecurie Bleue',64),(DEFAULT,'Société R.V.',64),(DEFAULT,'J.M. Skeffington',138),(DEFAULT,'Adler',3),(DEFAULT,'Émile Darl''mat',64),(DEFAULT,'A.C. Scott',138),
(DEFAULT,'M.K.H. Bilney',138),(DEFAULT,'H. Lesbros',64),(DEFAULT,'Yves Giraud-Cabantous',64),(DEFAULT,'R.H. Eccles',138),(DEFAULT,'André Parguel',64),(DEFAULT,'Raymond de Saugé Destrez',64),
(DEFAULT,'Jacques Savoye',64),(DEFAULT,'Team Autosports',138),(DEFAULT,'R. Marsh',138),(DEFAULT,'Frazer Nash',138),(DEFAULT,'Jacques Seylair',64),(DEFAULT,'Ecurie Eudel',64),
(DEFAULT,'Eugéne Chaboud',64),(DEFAULT,'André M. Embiricos',70),(DEFAULT,'BMW',3),(DEFAULT,'David Murray',138),(DEFAULT,'René Kippeurt',64),(DEFAULT,'Gaston Serraud',64),
(DEFAULT,'Jean Prenant',64),(DEFAULT,'Ecurie Lapin Blanc',138),(DEFAULT,'Victor Camerano',64),(DEFAULT,'Victor Camerano',64),(DEFAULT,'Miss P.M. Fawcett',138),(DEFAULT,'Robert P Hichens',138),
(DEFAULT,'Robert P Hichens',138),(DEFAULT,'Pierre Ferry',64),(DEFAULT,'Mme Fernande Roux',64),(DEFAULT,'Georges Monneret',64),(DEFAULT,'Marcel Horvilleur',64),(DEFAULT,'Miss Dorothy Stanley-Turner',138),(DEFAULT,'Raoul Forestier',64),
(DEFAULT,'Charles Morrison',138),(DEFAULT,'Jean-Pierre Wimille',64),(DEFAULT,'Ecurie Walter Watney',138),(DEFAULT,'Lagonda Ltd.',138),(DEFAULT,'Lord Selsdon',138),(DEFAULT,'Count Heyden',138),
(DEFAULT,'Joseph Chotard',64),(DEFAULT,'Robert Peverell Hichens',138),(DEFAULT,'Mrs. Majorie Fawcett',138),(DEFAULT,'Arthur W. Jones',138),(DEFAULT,'Ecuria Francia',64),(DEFAULT,'Victor Polledry',64),
(DEFAULT,'Robert Mazaud',64),(DEFAULT,'Archie Scott Brown',138),(DEFAULT,'Ecurie Francia',64),(DEFAULT,'T.A.S.O. Mathieson',138),(DEFAULT,'Jean Trémoulet',64),(DEFAULT,'Miles Collier',58),
(DEFAULT,'André Bellecroix',64),(DEFAULT,'Peter Mitchell-Thomson, Lord Selsdon',138),(DEFAULT,'Henri Louveau',64),(DEFAULT,'Mrs. P. Trevelyan',138),(DEFAULT,'W.S. Watney',138),
(DEFAULT,'Pierre Meyrat',64),(DEFAULT,'H.S.F. Hay',138),(DEFAULT,'Arthur Jones',138),(DEFAULT,'HRG Engineering',138),(DEFAULT,'René Bouchard',64),(DEFAULT,'Robert Lawrie',138),
(DEFAULT,'Monopole-Poissy',64),(DEFAULT,'N.J. Mahé / R. Crovetto',64),(DEFAULT,'Let-Aviation',55),(DEFAULT,'Auguste Lachaize',64),(DEFAULT,'Ecurie Verte',64),(DEFAULT,'Jacques Poch',64),
(DEFAULT,'Henry Leblanc',64),(DEFAULT,'Jack Bartlett',138),(DEFAULT,'André Guillard',64),(DEFAULT,'Auguste Veuillet',64),(DEFAULT,'Mrs. R.P. Hichens',64),(DEFAULT,'Ecurie Charles Pozzi',64),
(DEFAULT,'René Bonnet',64),(DEFAULT,'G.E. Phillips',138),(DEFAULT,'R.R.C. Walker Racing Team',138),(DEFAULT,'Etablissements Delettrez',64),(DEFAULT,'Écurie France',64),(DEFAULT,'Mme Vivianne Elder',64),
(DEFAULT,'Robert Redge',64),(DEFAULT,'Ecurie Lapin Blanche',138),(DEFAULT,'Marc Versini',64),(DEFAULT,'J.A. Plisson',64),(DEFAULT,'Peter Monkhouse',138),(DEFAULT,'Robert Tocheport',64),
(DEFAULT,'Dudley C. Folland',138),(DEFAULT,'Ecurie Rosier',64),(DEFAULT,'Camille Hardy',64),(DEFAULT,'Aston Martin Lagonda Ltd.',138),(DEFAULT,'Louis Eggen',18);